# Generated by Django 6.1 on 2026-08-24 03:39

from django.db import migrations

COMMON_INGREDIENTS = [
    ('豚肉', '肉'),
    ('鶏肉', '肉'),
    ('牛肉', '肉'),
    ('ひき肉', '肉'),
    ('鮭', '魚'),
    ('たまご', '卵・乳製品'),
    ('牛乳', '卵・乳製品'),
    ('チーズ', '卵・乳製品'),
    ('玉ねぎ', '野菜'),
    ('にんじん', '野菜'),
    ('じゃがいも', '野菜'),
    ('キャベツ', '野菜'),
    ('もやし', '野菜'),
    ('トマト', '野菜'),
    ('ピーマン', '野菜'),
    ('ねぎ', '野菜'),
    ('豆腐', '大豆製品'),
    ('納豆', '大豆製品'),
    ('米', '主食'),
    ('パン', '主食'),
]


def seed_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('ingredients', 'Ingredient')
    for name, category in COMMON_INGREDIENTS:
        Ingredient.objects.get_or_create(name=name, defaults={'category': category})


def unseed_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('ingredients', 'Ingredient')
    names = [name for name, _ in COMMON_INGREDIENTS]
    Ingredient.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_ingredients, unseed_ingredients),
    ]
