# Generated by Django 6.1 on 2026-08-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年齢')),
                ('likes', models.TextField(blank=True, verbose_name='好きな食べ物')),
                ('dislikes', models.TextField(blank=True, verbose_name='苦手な食べ物')),
                ('allergies', models.TextField(blank=True, verbose_name='アレルギー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='保護者')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
