# Generated by Django 6.1 on 2026-08-26

from django.db import migrations

CONDITIONS = ['子供向け', '時短']


def seed_conditions(apps, schema_editor):
    Condition = apps.get_model('recipes', 'Condition')
    for name in CONDITIONS:
        Condition.objects.get_or_create(name=name)


def unseed_conditions(apps, schema_editor):
    Condition = apps.get_model('recipes', 'Condition')
    Condition.objects.filter(name__in=CONDITIONS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_conditions, unseed_conditions),
    ]
